### ISSUE TITLE
Incorporate linting in CI

### ISSUE THREAD

**Issue by namoscato** [Maxim-Mazurok/google-api-typings-generator#11]
[`namoscato:ci...ci-lint`](https://github.com/namoscato/google-api-typings-generator/compare/ci...namoscato:ci-lint) prototypes build / linting CI, and [here is an example run](https://github.com/namoscato/google-api-typings-generator/commit/8a5bb2f0dd033e54134964b1cb47238d2a29eb3b/checks?check_suite_id=379045990) which is currently failing.

Thoughts on this approach and how it could relate to generating these type definitions automatically longterm?

**Comment by Maxim-Mazurok** [comment]
Awesome, I like your approach!
Maybe it would be even better to lint right after each API types generation.
So that instead of waiting for all types to generate first and only then start linting, we could speed fail-and-fix cycle.
For example, if the first typing linting fails, it means that we don't have to fetch and generate all other typings.

Regarding fails during linting, I guess, it's because we've added more tests with @declanvong 
I'm working on fixes, have a good progress already, will open PR later today.

**Comment by namoscato** [comment]
> For example, if the first typing linting fails, it means that we don't have to fetch and generate all other typings.

Yeah, this makes sense for sure.

Per https://github.com/Maxim-Mazurok/google-api-typings-generator/issues/7#issuecomment-570503026

> Regarding CI and testing, I think that DefinetlyTyped tests are good enough, as they perform tests with earlier TS versions.

I was also looking into how they did this as it would be ideal for this linting CI to leverage the same functionality. Some things seemed a bit specific for their publishing mechanism, but we can hopefully make something work.

I'll cleanup the prototype I started and open a pull request.
