### ISSUE TITLE
Automatically generate updated typings

### ISSUE THREAD

**Issue by namoscato** [Maxim-Mazurok/google-api-typings-generator#15]
Somewhat related to https://github.com/Maxim-Mazurok/google-api-typings-generator/issues/11 but opening a dedicated issue to start discussion.

Some initial thoughts / questions:

1. When should this happen? It would be nice to understand when a Google API changes, which could trigger a build. But any changes to the core generator would ideally regenerate _all_ typings.
2. Would this automatically open DefinitelyTyped PRs? Should we chat with some DefinitelyTyped maintainers before getting too far down this path? Perhaps we could start with just automatically generating the types in a separate branch within this repository? That would probably be a forward-compatible approach to iterate on as well.

**Comment by Maxim-Mazurok** [comment]
>     1. When should this happen?

After quick googling I can't find anything that would cover updates of all google APIs. They have [RSS](https://developers.google.com/maps/documentation/javascript/feeds/releases.xml) for Maps and they update maps API at least [weekly](https://developers.google.com/maps/documentation/javascript/versions#choosing-the-weekly-channel)

So, no webhook, as far as I know. That means that we should set up some cron-like job that will generate typings once a day/week and then use diff to detect if anything changed. If it would be too frequent - we could skip changes in comments and only update when changes to actual code happen. I've seen them doing massive rewording in comments after one of updates, which is not really important.

It would be interesting to make a script and let it run on the server for some time to collect some real-life data about how frequent API changes are. I would like to do it and I have server that runs 24/7, but if also want to do it - go ahead, just make sure to open PR with this script as I also would like to play with it.

>     2. Would this automatically open DefinitelyTyped PRs?

It's hard to tell without the experiment mentioned above. If changes are made more than once a week - it might not be a good idea to update typings every day. But I think that some popular libraries do update every day, as well as their typings. Anyway, I think we should conduct the experiment first, so that we can say DT team how frequent updates will be.

Another thought - don't open new PRs for the same API if another one is still open. But update the open PR instead. We should think about this when automating. But automating is definitely the way to move forward.

**Comment by namoscato** [comment]
> That means that we should set up some cron-like job that will generate typings once a day/week and then use diff to detect if anything changed.

Yeah, this sounds like a good approach to me. For what it's worth, GitHub Actions has the ability to [schedule workflow runs](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows#scheduled-events-schedule).

> It would be interesting to make a script and let it run on the server for some time to collect some real-life data about how frequent API changes are. I would like to do it and I have server that runs 24/7

Feel free to do this! If I do anything, it will just be some prototyping around generating the types and pushing the build to a separate branch on push to `master`. I think we will need this mechanism regardless, and then we can figure out how to trigger something like that when the APIs are updated externally.

**Comment by Maxim-Mazurok** [comment]
> For what it's worth, GitHub Actions has the ability to [schedule workflow runs](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows#scheduled-events-schedule).

That's great! I think we can make it work. Will have to add my github token, I think GitHub has some kind of [secret storage](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets) in project settings for this purpose.

> I think we will need this mechanism regardless, and then we can figure out how to trigger something like that when the APIs are updated externally.

It sounds fine to add types to the repo, but I'm not sure I understand why we'll need this. As far as I understand, we don't have to store actual typings in this repo, we only have to generate it and then make PR to DefinetlyTyped. Do you have other ideas in mind?

**Comment by namoscato** [comment]
> It sounds fine to add types to the repo, but I'm not sure I understand why we'll need this.

Well, I think it would enable us to more easily understand the differences between the generated types, especially as the generator source code changes.

**Comment by Maxim-Mazurok** [comment]
Right, I thought that versioning of typings in DefinetlyTyped repo would be sufficient for historical purposes. But now I see that it would make more sense to store them in our repo too to make it easier to see diffs during development :+1:

**Comment by Maxim-Mazurok** [comment]
BTW, while running experiments, I noticed that Discovery API returns methods not in the same order, so I had to use [deep-sort-object](https://www.npmjs.com/package/deep-sort-object) before comparing old and new API version. I think we should also use it (or some similar) approach for typings generation as well, so that we won't get tons of false-changes.

**Comment by Maxim-Mazurok** [comment]
Here's what I have gathered so far: [gist](https://gist.github.com/Maxim-Mazurok/7b87a6b77f88b106140f5ed1a296006a)

Takeouts: sometimes, only `revision` number changes. Sometimes, `etag` also changes.

Maybe, we should include `revision` in our generated typings and check that newly generated typings have `revision` newer than the previous one.

**Comment by namoscato** [comment]
> Maybe, we should include `revision` in our generated typings and check that newly generated typings have `revision` newer than the previous one.

This sounds good from my perspective and would simplify how we would determine if a project has changed.

It looks like their revisions are effectively dates. Do we have any thoughts as to how that could relate to the generate type versions (which are semantic [per DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library))?

**Comment by Maxim-Mazurok** [comment]
> Do we have any thoughts as to how that could relate to the generate type versions (which are semantic [per DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library))?

First option is to bump minor version of typings in the header after every new revision.
But we have some APIs that have minor version already (adexchangebuyer, for example).

Second option is to just specify revision number after the semantic header, so it will only be shown as a regular comment in typings.

I think that second approach is the safest, because even if we use minor version for something like google sheets (which only has major `4.0` version as of now) there's no guaranties that google won't publish `4.1` in the future. Obvious drawback, is that it won't be parsed by DT.

Using patch versions would be almost perfect solution, but unfortunately, using it gives the following error when testing typings:
```
Error parsing header. Expected: foo MAJOR.MINOR (patch version not allowed)
```
because for validation they use `strict` flag which bans patch version usage. It doesn't bad it during the generation phase, but it doesn't really change anything.

On a side note, I don't understand why they would want to ban patch version. I'll open an issue later just out of curiosity, but don't expect that it's a subject to change.

**Comment by namoscato** [comment]
> I don't understand why they would want to ban patch version.

Probably because they increment the patch version automatically as part of their build process.

I didn't realize we were _already_ parsing the discovery schema's (semantic) version. That seems correct, and I agree that we should just include revision for our purposes elsewhere. Other options:

1. We could include it as a fragment identifier to the generated discovery URL comment, i.e.

    ```
    // Generated from: https://www.googleapis.com/discovery/v1/apis/adexchangebuyer/v1.4/rest#20191204
    ```

2. We could add a formatted JSON metadata file that includes some of this stuff. That would certainly be easier to parse.

**Comment by Maxim-Mazurok** [comment]
> Probably because they increment the patch version automatically as part of their build process.

Oh, right, thank!

>     1. We could include it as a fragment identifier to the generated discovery URL comment, i.e.

Good idea, but I think it might be confusing, because it doesn't say that it's revision number.

>     2. We could add a formatted JSON metadata file that includes some of this stuff. That would certainly be easier to parse.

I like this approach, but unless we need any other metadata, it might be an overkill.

Let's add a new comment line, like this:
```js
// Generated from: https://sheets.googleapis.com/$discovery/rest?version=v4
// Revision: 20191204
```
And we could easily parse it using [`/^\/\/ Revision: (\d{8})$/gm`](https://regex101.com/r/LfWrDx/1)

This way, when user Ctrl+clicks method, IDE will open definitions file and revision version will be there, so he doesn't have to go find another metadata file to check revision, and it's still easy and safe to parse.

**Comment by namoscato** [comment]
Alright @Maxim-Mazurok, I think we're in a pretty good spot now to get this going.

As a next step, thoughts on getting a script going that updates a forked `DefinitelyTyped/DefinitelyTyped` with the generated type definition(s) in the `types` branch?

Certainly some specifics to work through; here are some scattered thoughts / questions:

* Perhaps we just start with a single service or at most a whitelisted set of services that are already in `DefinitelyTyped` to see how this goes?
* Should we create a separate `DefinitelyTyped` branch for each service / update (i.e. analogous to Dependabot)?
* We'll probably have to keep the forked `DefinitelyTyped/master` up to date.

Let me know what you think and if you have any other thoughts.

**Comment by Maxim-Mazurok** [comment]
I agree, we're pretty much ready :)
Sorry it's taking so long, I moved to Sydney, started new job and don't have my PC from home here, but I'll try to do my best to get into the action ASAP :)

Regarding your thoughts,
> * Perhaps we just start with a single service or at most a whitelisted set of services that are 
already in `DefinitelyTyped` to see how this goes?

Yes, that's a good idea. Probably we should start with one service, and if it goes well - whitelist others and then add new ones.

> * Should we create a separate `DefinitelyTyped` branch for each service / update (i.e. analogous to Dependabot)?

It's a good question. I couldn't find if DT supports multiple package updates in single PR. Still, I think that by having one PR - one package approach it would be easier to get them reviewed and also I'm not sure that their bot is capable of dealing with multiple package updates. So, yes, let's go with separate branches per service.

> * We'll probably have to keep the forked `DefinitelyTyped/master` up to date.

Yes, we have to. Not because we care about other definitions, but because we want to make sure that tests are updated and typings are still passing them.

**Comment by namoscato** [comment]
Sounds good, and no worries!

I might have time to prototype something this weekend. Assuming we'll want to keep the DefinitelyTyped fork under your username, could you fork it and add me as a collaborator?

**Comment by Maxim-Mazurok** [comment]
Yes, definitely!

I'm going to sketch the update scheme on the weekend in more details, but for now, that's what I have in mind:

- Create fork of DT
- Add action with `on: schedule: cron: ...` to run every X days to DT fork
- This action will:
  - update DT fork (how? GH API?)
  - generate fresh types
  - run DT linter/tests (for all new typings, I think DT testing tool will only run tests on modified files by default, so we don't have to delete other typings)
  - IF types differ:
    - IF we have open PR for specific package:
      - find branch
      - update typings
    - OTHERWISE:
      - create appropriate branches
      - add freshly generated typings to corresponding branch
      - open PRs to main DT repo

If you could investigate how we can update repo and open PRs using GH API to other means - it would be a great help.
Also, let me know if you want to add or edit anything in the scheme above. Now I'll go create fresh DT fork and share it with you.

**Comment by Maxim-Mazurok** [comment]
Another thing to think about: do we want to delete branches after merge (as dependabot do) or just keep them for future updates? I think keeping them would be easier, but then we have to check if branch exists before creating a new one.

**Comment by namoscato** [comment]
This sounds solid! I few thoughts:

> update DT fork (how? GH API?)

It might be easiest to setup a GitHub Action in `Maxim-Mazurok/DefinitelyTyped` that pulls `upstream/master` on a cron. I think there are some existing actions that effectively do this out of the box. Then, anytime a type definition is updated, we could ensure we always merge `origin/master` into that branch?

> run DT linter/tests

Thoughts on building this automation such that it references the already-generated `types` branch? Ideally we can assume those types have already been linted, which might simplify the process.

> do we want to delete branches after merge (as dependabot do) or just keep them for future updates?

Yeah, I think we can just leave them around. Dependabot also includes versions in their branches, but that also seems overkill to me. Branch names the correspond to the service name should suffice?

**Comment by Maxim-Mazurok** [comment]
> It might be easiest to setup a GitHub Action in `Maxim-Mazurok/DefinitelyTyped` that pulls `upstream/master` on a cron. I think there are some existing actions that effectively do this out of the box.

While it might work 99% of the time, I still think that it's better to ensure that we use the latest DT code before opening PRs. Unless Cron would run like every minute, which is also an option.

> Then, anytime a type definition is updated, we could ensure we always merge `origin/master` into that branch?

Right, I think we should add it to the algorithm between "find branch" and "update typings". Good catch!

Also, we can do the same for new typings, after creating a new branch. And because the list of APIs would eventually be pretty static - we might not need to update master at all, only other branches if that's possible.

> Thoughts on building this automation such that it references the already-generated `types` branch? Ideally we can assume those types have already been linted, which might simplify the process.

Well, DT testing might differ from our testing at the moment. But more importantly, our types branch is only updated when there's PR to this repo. Which is not sufficiently frequent. So, we should generate and test types in DT fork action.

> Branch names the correspond to the service name should suffice?

Branch name should be the same as typing folder name. Some of them have version, like beta/alpha, etc. Edge case would be if Google will introduce "master API" 😅 To be safe, we might want to add prefix, like "type-master" or "type-sheets", but it might be overkill :)

**Comment by namoscato** [comment]
We should definitely sketch something out visually as this is a nontrivial algorithm with a decent amount of moving parts!

**Comment by Maxim-Mazurok** [comment]
Hey, @namoscato!
I modified the above scheme quite a bit and made two flow-charts on separate pages in draw.io that you can check out [here](https://www.draw.io/?lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1&title=GAPI%20TS%20Auto-update.drawio#Uhttps%3A%2F%2Fdrive.google.com%2Fa%2Fmazurok.com%2Fuc%3Fid%3D1PtpkfQoeTZmZnUsrQ1X28ZrVHyDEdr1i%26export%3Ddownload)
First one is for DT fork, second one is for this repo.
Let me know what you think!

**Comment by namoscato** [comment]
@Maxim-Mazurok, sorry for the delay, and thank you for putting these together! This all sounds pretty good to me, and I think we can get started.

For the **DefinitelyTyped fork**:

* I'm wondering _where_ this script should actually be written / run? While it certainly needs to push changes to that fork, I don't think we want our script or even GitHub Action configuration in that repository.
* Perhaps a first pass just creates a DefinitelyTyped branch given a Google service name, and we can see how that plays out?

For **this repository**: If I am understanding correctly, do we just need to add a [schedule trigger](https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#onschedule) to the existing [build workflow](https://github.com/Maxim-Mazurok/google-api-typings-generator/blob/master/.github/workflows/build.yml)?

**Comment by Maxim-Mazurok** [comment]
> _where_ this script should actually be written / run? 

Yes, it probably should be written and ran in this repo, good catch! I was thinking to include it in DR fork, but now I see your point.

> Perhaps a first pass just creates a DefinitelyTyped branch given a Google service name, and we can see how that plays out?

Yeah, on the first run we probably should not open PR to DT automatically, just in case if it opens 100 of them :)

> For **this repository**: If I am understanding correctly, do we just need to add a [schedule trigger](https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#onschedule) to the existing [build workflow](https://github.com/Maxim-Mazurok/google-api-typings-generator/blob/master/.github/workflows/build.yml)?

Pretty much so, but I'm doing a little bit of refactoring for our actions. And we'll have to include linting into the scheduled build, according to scheme.

**Comment by namoscato** [comment]
Other than https://github.com/Maxim-Mazurok/google-api-typings-generator/pull/70#issuecomment-591921033, I don't have any additional thoughts at the moment.

Let me know if you would like any help on the DefinitelyTyped script!
