### ISSUE TITLE
 Namespace 'gapi.client' has no exported member 'calendar'

### ISSUE THREAD

**Issue by romanKrds** [Maxim-Mazurok/google-api-typings-generator#216]
Hi! Could anyone assist me with the types for google calendar API? I'm trying to use it in my Angular 9 app and couldn't succeed in it. I get an error ` Namespace 'gapi.client' has no exported member 'calendar'` when importing a type like so `import Event = gapi.client.calendar.Event;`, however, I can use all of the interfaces if I suppress the error with ts-ignore. These are the types I've installed:
- "@types/gapi": "^0.0.39"
- "@types/gapi.auth2": "^0.0.51"
- "@types/gapi.client.calendar": "^3.0.4"

**Comment by Maxim-Mazurok** [comment]
Hello @romanKrds, thank you for submitting this issue and sorry for the late reply!
Yes, I definitely can help you with that.
I just created a blank Angular 9 project and has similar issue.
It seems like they have three different `tsconfig.json` files:
1. `tsconfig.app.json`
2. `tsconfig.json`
3. `tsconfig.spec.json`

Depending on your use-case, you have to check that they use `types` correctly.

For example, out-of-the-box `tsconfig.app.json` has `types: []`. Which basically means that TS will not try to find any types in the default `node_modules/@types` folder.
You should either remove `types: []` line completely to include all types automatically, or add `types: ["gapi", "gapi.auth2", "gapi.client.calendar"]` in order to include these types explicitly.

Also, check other `tsconfig` files as well.

Here's my working `tsconfig.app.json`:
```json
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "./out-tsc/app",
  },
  "files": [
    "src/main.ts",
    "src/polyfills.ts"
  ],
  "include": [
    "src/**/*.d.ts"
  ]
}
```
and `tsconfig.json`:
```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "module": "esnext",
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2015",
    "lib": [
      "es2018",
      "dom"
    ]
  },
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true
  }
}
```

Let me know If that helps!

**Comment by romanKrds** [comment]
@Maxim-Mazurok, thank you so much! This solution works like a charm)

**Comment by Maxim-Mazurok** [comment]
Consider starring a repo, thank you ☺️

**Comment by Maxim-Mazurok** [comment]
Here's an example project for future references: https://github.com/Maxim-Mazurok/angular-google-calendar-typescript-example
