### ISSUE TITLE
Cleaning stale branches

### ISSUE THREAD

**Issue by HoldYourWaffle** [Maxim-Mazurok/google-api-typings-generator#302]
There are a lot of branches in this repository, most of which are not actively used. It'd probably be a good idea to clean these up.

These branches have been fully merged:
- `documentation-link`
- `pr-template-update`
- `rm-form-data-dep`
- `add-license-1`
- `create-or-reset`
- `octokit-types`
- `Maxim-Mazurok-patch-1`
- `check-before-push`
- `no-pr-revision-only`

The PR for these branches have been closed:
- `apigee`
- `api-diff-logger`
- `declan/deduplicate-request-types-2`
- `jb-gitignore`

Leaving just these branches open:
- `master` (obviously)
- `types` (obviously)
- `declan/deduplicate-request-types` (#166)
- `declan/merge-declanvong-changes` (last updated 8 months ago, 584 commits behind / 2 commits ahead)
- `DefinitelyTyped` (last updated 3 years ago, 625 commits behind / 18 commits ahead)

I'd also propose moving the `types` branch to a different repository.
I'd love to keep up-to-date with all the conversations in this module, but if I "watch" the repository my homepage is spammed with automatic deployments. I guess it would also probably improve gits performance, since the respository's size will be significantly smaller.
I don't know how the auto-deploy logic works, but this could be as simple as just changing a remote URL somewhere. All history should automatically be "copied" and preserved.

**Comment by Maxim-Mazurok** [comment]
Great job, we needed a bit of a clean-up :)

- `apigee` - contains (possibly) useful fix, but it was abandoned since Apigee doesn't seem to be something that one would use on the client-side. So, it's "archived" until later.
- `api-diff-logger` - I'd like to leave it for historical purposes, it used to run on my server for a while, to investigate how often and what changes in schemas. this might come in handy if we would ever need this again.
- `declan/deduplicate-request-types` - waits for @declanvong's PR to be fixed and merged
- `declan/deduplicate-request-types-2` - @declanvong should probably delete it unless it contains something useful for #166
- `jb-gitignore` - was created for #21 but we decided to leave this IDE specific stuff, so I'm deleting it. BTW, circumstances forced me to move to VS Code and unlike `.idea` folder from JetBrains, some VS Code config makes a lot more sense to be stored in the repo. Like suggested extensions and run/debug scripts. I'll create an issue for this, thanks for reminding :)

I'm also deleting all fully merged branches, thanks for compiling this list! I guess the only reason I was keeping them is that I might've linked to them somewhere and didn't want to break links. But I guess it's not as important as maintaining clean repo.

> moving the types branch to a different repository

It's a good idea. All deployment happens in [auto-generate](https://github.com/Maxim-Mazurok/google-api-typings-generator/blob/master/.github/workflows/auto-generate.yml): we generate types, we lint them and in case if everything went well - we deploy them using [peaceiris/actions-gh-pages@v2](https://github.com/peaceiris/actions-gh-pages). We should upgrade to `v3` and use [`external_repository`](https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-deploy-to-external-repository-external_repository) to publish them to a different repo. I will create an issue for this.

**Comment by Maxim-Mazurok** [comment]
By the way, I'm not getting spammed about failing deployments on the homepage, I'm getting them via email.
Perhaps, it's different for contributors... Sorry about that.

**Comment by HoldYourWaffle** [comment]
> I'm getting them via email

That's arguably even worse.

> Sorry about that.

No worries! Just be sure to notify me once this is "fixed", so I can start watching this amazing project again 😉

**Comment by declanvong** [comment]
>declan/deduplicate-request-types - waits for @declanvong's PR to be fixed and merged

Ooh, thanks for the ping... it keeps falling off my radar 🙈
