### ISSUE TITLE
Decrease minimum TypeScript version

### ISSUE THREAD

**Issue by namoscato** [Maxim-Mazurok/google-api-typings-generator#7]
Per https://github.com/DefinitelyTyped/DefinitelyTyped/pull/40407#discussion_r361498728, we might consider decreasing the generated TypeScript version. It would be cool to add some CI to ensure the generated types are compatible across versions.

_See [I want to use features from TypeScript 2.9 or above.](https://github.com/DefinitelyTyped/DefinitelyTyped#i-want-to-use-features-from-typescript-29-or-above)_

**Comment by Maxim-Mazurok** [comment]
You're right, I bumped version because of a habit :) Didn't know that it was the minimum required version, rather then preferred version of sorts.
AFAIK, we're not using any new feature, I'll test it with earlier versions manually and will make PR.

Regarding CI and testing, I think that DefinetlyTyped tests are good enough, as they perform tests with earlier TS versions. I'll have a look at how this is dealt with in other typings repos. I think we should try to somehow use tests directly from DefinetlyTyped. Let me know if you have any ideas on this or another implementation. Thanks!

**Comment by Maxim-Mazurok** [comment]
@namoscato I tested all freshly generated typings with TypeScript Version 2.1+ and it worked.
Only 2.0 didn't, because it doesn't support `async` used in our tests.

I managed to do this by using modified `dtslint` version that I made to run tests using unsupported versions. Only 2.8 and later are supported right now. So, it will be quite hard to run CI with this modified version to test unsupported TS versions.

That being said, I think it's best for the project to set minimum required version to 2.8 as it will require too much effort to support older versions and there were no requests for that. If anybody uses our typings with older TS versions - please, let me know in the comment.
