### ISSUE TITLE
Document how to use typings from the types branch

### ISSUE THREAD

**Issue by EdricChan03** [Maxim-Mazurok/google-api-typings-generator#85]
Currently, the type definitions are automatically deployed to the `types` branch. However, there's no documentation that indicates how to use the generated type definitions in a project.

**Comment by Maxim-Mazurok** [comment]
Good point, @EdricChan03 !
`types` branch is just a temporary measure, while we're working on automated updates of all `@types/gapi.client.*` on npm.
It takes more time than I originally thought, so it might be actually good to have documentation on `types` branch while we're working on #74 

Here's a quick summary:
1. Download [types branch](https://codeload.github.com/Maxim-Mazurok/google-api-typings-generator/zip/types), extract APIs that you need and put them in your project, like so:
```
- you-app <-- root folder of your app
  - types
    - gapi.client.sheets <-- this one is from `types` branch
      - index.d.ts
      - <other files>
  - package.json <-- other files that you have in root of your project
  - tsconfig.json <-- other files that you have in root of your project
```

**Comment by Maxim-Mazurok** [comment]
Good point, @EdricChan03 !
`types` branch is just a temporary measure, while we're working on automated updates of all `@types/gapi.client.*` on npm.
It takes more time than I originally thought, so it might be actually good to have documentation on `types` branch while we're working on #74 

Here's a quick summary:
1. Download [types branch](https://codeload.github.com/Maxim-Mazurok/google-api-typings-generator/zip/types), extract APIs that you need and put them in your project, like so:
```
- your-app <-- root folder of your app
  - types
    - gapi.client.sheets <-- this one is from `types` branch
      - index.d.ts
      - <other files>
  - package.json <-- other files that you have in root of your project
  - tsconfig.json <-- other files that you have in root of your project
```
2. Add [`typeRoots`](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#types-typeroots-and-types) to your `tsconfig.json`:
```json5
{
  "compilerOptions": {
    "typeRoots": [
      "./node_modules/@types",
      "./types" // <-- key point, add your custom type definitions directory, created in the 1st step
    ]
  }
}

```

Let me know if it works for you, I haven't tested it.
Also, feel free to open PR if you found another way that worked for you!
Otherwise, I'll be happy to test and update instructions for you and later include them in docs.
Thank you for your contribution!

**Comment by EdricChan03** [comment]
What about publishing the typings to the repository's [GitHub Packages](https://help.github.com/en/packages/using-github-packages-with-your-projects-ecosystem/configuring-npm-for-use-with-github-packages)?

**Comment by Maxim-Mazurok** [comment]
This is interesting! It seems like we can use GitHub Packages for "nightly" builds of types without requiring reviews by DefinetlyTyped team. I will totally look into this, I think we can do this before #74 Thanks for the idea!

**Comment by Maxim-Mazurok** [comment]
Since #74 was done, there's no need in this. We can use types from DT because they are updated almost instantly.
If your type is not being updated in DR - we have to add it to the list of supported types in this repo.
Refer to this comment: https://github.com/Maxim-Mazurok/google-api-typings-generator/issues/363#issuecomment-701138569
