### ISSUE TITLE
@types/gapi.client.discovery deprecated

### ISSUE THREAD

**Issue by DigitalNaut** [Maxim-Mazurok/google-api-typings-generator#885]
```bash
WARN  deprecated @types/gapi.client.discovery@1.0.9: use @types/gapi.client.discovery-v1 instead
```

I keep getting this warning and I'm not sure how to resolve it. Would it be possible to update the dependency for @maxim_mazurok/gapi.client.drive-v3?

Many thanks! Awesome generator, btw.

Edit: Sorry, I made a mistake, there are too many similar packages and I'm kind of new to this. It seems that the package giving the warning is @types/gapi.client.drive-v3 that is somehow related to @maxim_mazurok/gapi.client.drive-v3 which doesn't provide the same typings when I swap them out.

**Comment by Maxim-Mazurok** [comment]
Hello! @types/gapi.* just references @maxim_mazurok/gapi.* packages.
The reason you couldn't swap them is because @types will be included in TS by default, while @maxim_mazurok of course isn't. Hence why we need that proxy/reference. Hope it makes more sense now :)

Either way, good point about deprecated package, we did switch to the @gapi.client.*-v* format and forgot to update our own dependencies :) Will do, thanks for raising the issue!

**Comment by Maxim-Mazurok** [comment]
Hey @DigitalNaut I have probably fixed the issue, it should be automatically released with the new version of @maxim_mazurok/gapi.client.drive-v3
This will happen when there's a new revision of the schema from google, judging by the version history it should happen within a week, let me know if you'll have any other questions or issues with types, cheers!

**Comment by DigitalNaut** [comment]
Amazing, thank you so much. Will do!
