### ISSUE TITLE
Move template files

### ISSUE THREAD

**Issue by namoscato** [Maxim-Mazurok/google-api-typings-generator#99]
At least:

* `readme.dot`
* `tsconfig.dot`
* `tslint.dot`

are in the root directory, which is confusing as they are not configuration for this repository.

Move these somewhere else for clarity – perhaps `src/templates`?

**Comment by Maxim-Mazurok** [comment]
Totally agree, it took me some time to realize that when I first started working on this fork :)
`src/templates` looks like a more appropriate place for them.
I'm also open to change the templating engine in favor of something more popular and reliable.
I remember deleting [tests.dot](https://github.com/Maxim-Mazurok/google-api-typings-generator/commit/b1ee4002c0acfd1ad63a0723e48113ab2a1feaaf#diff-189dc326050ccae7f96867f7c8483e22) because it had some kind of unfixable bug. I think it had something to do with `{{? !it.auth }}` and conditional rendering. It was working fine when I tried to decompose the code, but when I put all the pieces together - it acted weird.
